### ISSUE TITLE
installation not working with pip 20.1.1

### ISSUE THREAD

**Issue by Tjitskedv** [briney/abstar#85]
Hi,

Today I installed the abstar development version in a new account - using pip install https://github.com/briney/abstar/archive/development.zip  - hereby I ran into a problem with pip 20.1.1 - getting the error:

AttributeError: 'ParsedRequirement' object has no attribute 'req'

Using an older pip version 20.0.2 (pip install pip==20.0.2) the installation was succesfull. - so for now a fine solution but maybe good to look into.

kind regard

Tjitske

**Comment by sdvillal** [comment]
Also bit me today. Using pip internals is not supported by the pip folks, and so they are free to break things without remorse. See: https://github.com/pypa/pip/issues/8188

**Comment by briney** [comment]
This is fixed in v0.4.3, which is now on PyPI.
